version: '3.8'
volumes:
  db-store:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: ./ops/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run app/cmd/main.go
    environment:
      DB_HOST: 'db'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - db-store:/var/lib/postgresql/data
